version: "3.7"

services:
  nexus:
    image: sonatype/nexus3:3.58.0
    expose:
      - 8081
      - 8082
      - 8083
    ports:
      - "8082:8082"
      - "8083:8083"
      - "8081:8081"
    volumes:
      - /volume1/docker/nexus/nexus-data:/nexus-data
    restart: always
